version: "3.9"

include:
  - docker-compose.mongo.yml

services:
  ugc:
    build: ./ugc
    container_name: ugc
    env_file:
      - ugc/.env
    restart: 'always'
    expose:
      - "8000"
    depends_on:
      mongo-ugc-db:
        condition: service_started
      redis-ugc:
        condition: service_healthy
    profiles:
      - ugc_single
      - ugc_cluster
    networks:
      default:
      cinema_network:
        ipv4_address: 172.30.1.205
    healthcheck:
      test: [ "CMD-SHELL", 'curl -X GET --header "X-Request-Id: 1" -s http://ugc:8000/healthcheck || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 30s

  mongo-ugc-db:
    image: mongo
    container_name: mongo-ugc-db
    expose:
      - "27017"
    profiles: [ugc_single]

  redis-ugc:
    image: redis:7.2.3
    container_name: redis-ugc
    volumes:
      - redis_ugc_volume:/data
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - ugc_single
      - ugc_cluster


volumes:
  static_volume:
  redis_ugc_volume: