version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    profiles: [elk]
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET -s http://elasticsearch:9200/_cluster/health?pretty || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 30s
    restart: always

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    profiles: [elk]
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5601/api/status -o /dev/null || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 30s
    restart: always

  logstash:
    image: logstash:8.12.2
    environment:
      XPACK_MONITORING_ENABLED: "true"
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      ES_HOST: "elasticsearch:9200"
    volumes:
      - ./logstash/logstash.conf:/config/logstash.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    profiles: [elk]
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:5044/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 30s
    restart: always
  
volumes:
  elasticsearch_volume: