# Generated by Django 5.0.1 on 2024-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[("actor", "actor"), ("director", "director"), ("writer", "writer")], verbose_name="Role"
            ),
        ),
    ]
