# Generated by Django 5.0.1 on 2024-04-11 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'content"."subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFilmWork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork', verbose_name='filmwork')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription_filmwork',
                'verbose_name_plural': 'subscription_filmworks',
                'db_table': 'content"."subscription_film_work',
                'indexes': [models.Index(fields=['subscription_id'], name='subs_film_work_subs_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'subscription_id'), name='subs_film_work_film_work_id_subs_id_key'),
        ),
    ]
